steps:
  # Deploy directly from source using Google Cloud's managed build pipeline.
  # This command zips the source, uploads it, builds it (using the Dockerfile), 
  # and deploys it, handling the Artifact Registry creation automatically.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aegis-medical-website'
      - '--source'
      - '.'
      - '--region'
      - 'europe-west2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# Keep CLOUD_LOGGING_ONLY to prevent the previous logging bucket error
options:
  logging: CLOUD_LOGGING_ONLY
